### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by intelbg** [simonvik/libvmod_maxminddb#5]
Hello,
I see the following errors trying to compile the module:

./configure: line 12029: VARNISH_VMOD_INCLUDES: command not found
./configure: line 12030: VARNISH_VMOD_DIR: command not found
./configure: line 12031: VARNISH_VMODTOOL: command not found
checking for varnishtest... /usr/local/bin/varnishtest
checking for varnishd... /usr/local/sbin/varnishd
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
root@server [/usr/local/src/varnish-geoip-plugin-master/libvmod_maxminddb-master]# make
make  all-recursive
make[1]: Entering directory `/usr/local/src/varnish-geoip-plugin-master/libvmod_maxminddb-master'
Making all in src
make[2]: Entering directory `/usr/local/src/varnish-geoip-plugin-master/libvmod_maxminddb-master/src'
make[2]: *** No rule to make target `@VMODTOOL@', needed by `vcc_if.c'.  Stop.
make[2]: Leaving directory `/usr/local/src/varnish-geoip-plugin-master/libvmod_maxminddb-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/varnish-geoip-plugin-master/libvmod_maxminddb-master'
make: *** [all] Error 2

Is it compatible with CentOS and how can I fix these errors? I tryed compiling it for varnish 4 with VMOD_DIR and without VMOD_DIR?

**Comment by simonvik** [comment]
Sorry for ignoring/forgetting, it requires the dev-packages from varnish (at least on debain)

I havent tested it on anything but debian.

Its called libvarnishapi-dev in debian,
