### ISSUE TITLE
Incompatible pointer type warning on make

### ISSUE THREAD

**Issue by komodin** [simonvik/libvmod_maxminddb#8]
Hi,
When I run make I get these warnings:

> libvmod_maxminddb # make
> make  all-recursive
> make[1]: Entering directory `/root/libvmod_maxminddb'
> Making all in src
> make[2]: Entering directory `/root/libvmod_maxminddb/src'
> /usr/share/varnish-plus/vmodtool.py ../src/vmod_maxminddb.vcc
> /bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish-plus   -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c -o vcc_if.lo vcc_if.c
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish-plus -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c  -fPIC -DPIC -o .libs/vcc_if.o
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish-plus -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c -o vcc_if.o >/dev/null 2>&1
> mv -f .deps/vcc_if.Tpo .deps/vcc_if.Plo
> /bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish-plus   -g -O2 -MT vmod_maxminddb.lo -MD -MP -MF .deps/vmod_maxminddb.Tpo -c -o vmod_maxminddb.lo vmod_maxminddb.c
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish-plus -g -O2 -MT vmod_maxminddb.lo -MD -MP -MF .deps/vmod_maxminddb.Tpo -c vmod_maxminddb.c  -fPIC -DPIC -o .libs/vmod_maxminddb.o
> vmod_maxminddb.c: In function 'lookup':
> vmod_maxminddb.c:39:2: warning: passing argument 3 of 'MMDB_aget_value' from incompatible pointer type [enabled by default]
>   r = MMDB_aget_value(&s.entry, entry, path);
>   ^
> In file included from vmod_maxminddb.c:11:0:
> /usr/include/maxminddb.h:202:16: note: expected 'const char * const* const' but argument is of type 'const char *'
>      extern int MMDB_aget_value(MMDB_entry_s *const start,
>                 ^
> vmod_maxminddb.c: In function 'vmod_query_continent':
> vmod_maxminddb.c:83:2: warning: passing argument 4 of 'vmod_query_common' from incompatible pointer type [enabled by default]
>   return vmod_query_common(ctx, priv, ip, continent_path);
>   ^
> vmod_maxminddb.c:65:1: note: expected 'const char *' but argument is of type 'const char **'
>  vmod_query_common(const struct vrt_ctx *ctx, struct vmod_priv *priv, const struct suckaddr *ip, const char *path)
>  ^
> vmod_maxminddb.c: In function 'vmod_query_country':
> vmod_maxminddb.c:90:2: warning: passing argument 4 of 'vmod_query_common' from incompatible pointer type [enabled by default]
>   return vmod_query_common(ctx, priv, ip, country_path);
>   ^
> vmod_maxminddb.c:65:1: note: expected 'const char *' but argument is of type 'const char **'
>  vmod_query_common(const struct vrt_ctx *ctx, struct vmod_priv *priv, const struct suckaddr *ip, const char *path)
>  ^
> vmod_maxminddb.c: In function 'vmod_query_state':
> vmod_maxminddb.c:97:2: warning: passing argument 4 of 'vmod_query_common' from incompatible pointer type [enabled by default]
>   return vmod_query_common(ctx, priv, ip, state_path);
>   ^
> vmod_maxminddb.c:65:1: note: expected 'const char *' but argument is of type 'const char **'
>  vmod_query_common(const struct vrt_ctx *ctx, struct vmod_priv *priv, const struct suckaddr *ip, const char *path)
>  ^
> vmod_maxminddb.c: In function 'vmod_query_city':
> vmod_maxminddb.c:104:2: warning: passing argument 4 of 'vmod_query_common' from incompatible pointer type [enabled by default]
>   return vmod_query_common(ctx, priv, ip, city_path);
>   ^
> vmod_maxminddb.c:65:1: note: expected 'const char *' but argument is of type 'const char **'
>  vmod_query_common(const struct vrt_ctx *ctx, struct vmod_priv *priv, const struct suckaddr *ip, const char *path)
>  ^
> vmod_maxminddb.c: In function 'vmod_query_postalcode':
> vmod_maxminddb.c:111:2: warning: passing argument 4 of 'vmod_query_common' from incompatible pointer type [enabled by default]
>   return vmod_query_common(ctx, priv, ip, postalcode_path);
>   ^
> vmod_maxminddb.c:65:1: note: expected 'const char *' but argument is of type 'const char **'
>  vmod_query_common(const struct vrt_ctx *ctx, struct vmod_priv *priv, const struct suckaddr *ip, const char *path)
>  ^
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish-plus -g -O2 -MT vmod_maxminddb.lo -MD -MP -MF .deps/vmod_maxminddb.Tpo -c vmod_maxminddb.c -o vmod_maxminddb.o >/dev/null 2>&1
> mv -f .deps/vmod_maxminddb.Tpo .deps/vmod_maxminddb.Plo
> /bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99  -g -O2 -module -export-dynamic -avoid-version -lmaxminddb  -o libvmod_maxminddb.la -rpath /usr/lib64/varnish-plus/vmods/ vcc_if.lo vmod_maxminddb.lo
> libtool: link: gcc -std=gnu99 -shared  -fPIC -DPIC  .libs/vcc_if.o .libs/vmod_maxminddb.o   -lmaxminddb  -O2   -Wl,-soname -Wl,libvmod_maxminddb.so -o .libs/libvmod_maxminddb.so
> libtool: link: ar cru .libs/libvmod_maxminddb.a  vcc_if.o vmod_maxminddb.o
> libtool: link: ranlib .libs/libvmod_maxminddb.a
> libtool: link: ( cd ".libs" && rm -f "libvmod_maxminddb.la" && ln -s "../libvmod_maxminddb.la" "libvmod_maxminddb.la" )
> make[2]: Leaving directory `/root/libvmod_maxminddb/src'
> make[2]: Entering directory `/root/libvmod_maxminddb'
> rst2man README.rst vmod_geoip.3
> make[2]: Leaving directory `/root/libvmod_maxminddb'
> make[1]: Leaving directory `/root/libvmod_maxminddb'

I'm working on CentOS 7. I have this packages installed:
`libtool varnish-plus varnish-plus-libs varnish-plus-libs-devel python-docutils libmaxminddb libmaxminddb-devel`

Thanks!

**Comment by simonvik** [comment]
Should work better now, fixed warnings and a few other things. Feel free to try it out :)
